"""initial

Revision ID: 2c9a17839aae
Revises: 
Create Date: 2025-02-13 20:38:59.082938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9a17839aae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ball_speed', sa.Float(), nullable=False),
    sa.Column('angle_v', sa.Float(), nullable=False),
    sa.Column('angle_h', sa.Float(), nullable=False),
    sa.Column('carry', sa.Float(), nullable=False),
    sa.Column('roll', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('lateral', sa.Float(), nullable=False),
    sa.Column('spin', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings_table')
    # ### end Alembic commands ###
