"""add two new models

Revision ID: 8a3099fc8d0a
Revises: 2c9a17839aae
Create Date: 2025-03-19 19:51:27.468757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3099fc8d0a'
down_revision: Union[str, None] = '2c9a17839aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hsv_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(length=99), nullable=False),
    sa.Column('hue_min', sa.Integer(), nullable=False),
    sa.Column('hue_max', sa.Integer(), nullable=False),
    sa.Column('saturation_min', sa.Integer(), nullable=False),
    sa.Column('saturation_max', sa.Integer(), nullable=False),
    sa.Column('value_min', sa.Integer(), nullable=False),
    sa.Column('value_max', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_name')
    )
    op.create_table('pixel_distance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(length=99), nullable=False),
    sa.Column('pixels_per_cm', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pixel_distance')
    op.drop_table('hsv_settings')
    # ### end Alembic commands ###
