"""add club column to GolfShot

Revision ID: b14370c64d4f
Revises: d0544de31aa3
Create Date: 2025-06-28 16:05:14.045955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14370c64d4f'
down_revision: Union[str, None] = 'd0544de31aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings_table', sa.Column('club', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings_table', 'club')
    # ### end Alembic commands ###
