"""Add is_active column to HSVSetting and PixelDistance

Revision ID: dac5953070aa
Revises: 8a3099fc8d0a
Create Date: 2025-03-27 00:27:58.142584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac5953070aa'
down_revision: Union[str, None] = '8a3099fc8d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
