"""rename user_settings_table to golf_shots

Revision ID: fcb528f2806e
Revises: b14370c64d4f
Create Date: 2025-08-07 22:34:40.846576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb528f2806e'
down_revision: Union[str, None] = 'b14370c64d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_range_shots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club', sa.String(length=25), nullable=True),
    sa.Column('ball_speed', sa.Float(), nullable=False),
    sa.Column('angle_v', sa.Float(), nullable=False),
    sa.Column('angle_h', sa.Float(), nullable=False),
    sa.Column('carry', sa.Float(), nullable=False),
    sa.Column('roll', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('lateral', sa.Float(), nullable=False),
    sa.Column('spin', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_settings_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ball_speed', sa.FLOAT(), nullable=False),
    sa.Column('angle_v', sa.FLOAT(), nullable=False),
    sa.Column('angle_h', sa.FLOAT(), nullable=False),
    sa.Column('carry', sa.FLOAT(), nullable=False),
    sa.Column('roll', sa.FLOAT(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.Column('lateral', sa.FLOAT(), nullable=False),
    sa.Column('spin', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('club', sa.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drive_range_shots')
    # ### end Alembic commands ###
